### ISSUE TITLE
Final Release Checklist

### ISSUE THREAD

**Issue by gregziegan** [thebritican/annotation-editor#24]
- [x] Properly imports & exports images from Zendesk Editor App location
- [x] Add icons for new spotlight shapes
- [x] QA while writing tests
- [x] Change ellipse behavior, center should not be on start, but halfway from mouse start to end
~- Have a "large edit mode" with a new Zendesk App Location~
- [x] Write comments, documentation
- [x] Be able to upload your own images in a non-Zendesk context
- [x] Adjust stroke widths
- [x] Normalize icon sizes
- [x] Selected image in zendesk editor gets dropped immediately into annotator
- [x] Bring options into dropdowns
- [x] Blur
- [x] cute arrow

**Comment by alanhogan** [comment]
- [x] Export should render with the same font as preview 

↑ Personally think this is worth spending a little time on as nobody wants Times (and it changes the text dimensions)

**Comment by gregziegan** [comment]
- turn native browser tooltips into quicker to show tooltips
- determine a way to differentiate drawings from attributes in the control pane
- should be able to edit old drawings
- support attachment annotating with zendesk?

Edit: tracking the above in issues now

**Comment by alanhogan** [comment]
## Regarding editing previously saved drawings

### Goals

1. Allow users to pick up where they left off, adding, removing, or editing annotations
2. Information deletion / obscuration should not be compromised, though: if an image is sent to a user, the user should not be able to, themselves, remove an annotation and view the hidden information

### Approaches

- We can't store the original image in the saved PNG file due to goal number 2 (I am referring to the idea of making the png file include the original version as well via metadata)
- But we could store metadata in the saved PNG that includes a reference to the original image (some ref/ID etc) and a serialization of the annotations. Note that the ref to the original image can't be a URL for that image or an equivalent, again as it provides an easy way to defeat goal number 2.
- Alternatively that state could be preserved by GOAT locally or in GOAT memory instead of in the image. There would need to be some way to tie the updated image in the editor with this state though.

**Comment by gregziegan** [comment]
Made the following issues to track after 1.0.0 release.
https://github.com/thebritican/goat/issues/77
https://github.com/thebritican/goat/issues/78
https://github.com/thebritican/goat/issues/79
https://github.com/thebritican/goat/issues/80
https://github.com/thebritican/goat/issues/81
